export const WORDSENG = [
  'AGENT',
  'WORLD',
  'ABOUT',
  'HEART',
  'WATER',
  'SIXTY',
  'BOARD',
  'MONTH',
  'MUSIC',
  'PARTY',
  'PIANO',
  'MOUTH',
  'WOMAN',
  'SUGAR',
  'AMBER',
  'DREAM',
  'LAUGH',
  'TIGER',
  'EARTH',
  'MONEY',
  'WORDS',
  'SMILE',
  'LEMON',
  'SOUTH',
  'AFTER',
  'STONE',
  'THING',
  'LIGHT',
  'STORY',
  'POWER',
  'TODAY',
  'RANGE',
  'PEARL',
  'VENOM',
  'PROXY',
  'ROUND',
  'HOVER',
  'CANDY',
  'ABOVE',
  'PHONE',
  'OTHER',
  'SMART',
  'BLACK',
  'MAGIC',
  'FRUIT',
  'RADIO',
  'ROYAL',
  'HONEY',
  'FLAKE',
  'SOUND',
];

export const WORDSFR = [
  "PLAGE", "MARIN", "METRE", "TIARE", "TACHE", "LYCEE", "SCENE", "SALON", "REPOS", "POMME",
  "NUAGE", "FILLE", "MAINS", "MAINE", "TAXER", "RUGBY", "PALME", "JARDI", "CHAUD", "HORSE",
  "VALSE", "HOTEL", "JALON", "BEAUX", "TEMPS", "NOMME", "JOUER", "FLUTE", "LUCRE", "LAPIN",
  "TABLE", "CHIEN", "ROBOT", "GRAND", "BLANC", "NOIR", "VERTS", "LIVRE", "CORPS", "MURER",
  "CHAIR", "MAGIE", "REGLE", "TROIS", "FLEUR", "BAGUE", "MONTE", "VOILE", "CIELS"
]



